services:
  php:
    build:
      dockerfile: ./.docker/php/Dockerfile
    environment:
      CADDY_SERVER_EXTRA_DIRECTIVES: "tls /etc/caddy/certs/tls.pem /etc/caddy/certs/tls.key"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/php/conf/Caddyfile:/etc/caddy/Caddyfile:cached
    depends_on:
      - database
      - redis
      - opensearch
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
  database:
    image: mariadb:10.6.18
    env_file:
      - ./.docker/database/.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
  opensearch:
    build:
      dockerfile: ./.docker/opensearch/Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: ./.docker/opensearch/.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq:delegated
      - ./.docker/rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:delegated
    env_file: ./.docker/rabbitmq/.env
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  db_data:
  rabbitmqdata:
